#!/usr/bin/perl 

#
# NethServer Base
#

#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::ConfigDB;

# Initialize NUT password if not set

my $confdb = esmith::ConfigDB->open;
my $nut = $confdb->get('nut-server') or exit(1);
my $prop = $nut->prop('Password') || '';
if ($prop eq '') {
    my $rand = '';
    for (my $i=0; $i<15; $i++) {
        $rand .= int(rand(10));
    }
    $nut->set_prop('Password',$rand);
}
